### PR TITLE
guidePreset[] to create grids in the UI and showGuides Prop to toggle hide and show state for the grid lines [react-guides]

### PR DESCRIPTION
**Pull request by sajanthomas01**
- ~~Added a new prop **"guidePreset []"** which accept an array of numbers to plot lines in x and y-axis to create a **grid-like overlay** on the start of the application~~
- Added a new prop **"defaultGuides []"** which accept an array of numbers to plot lines in x and y-axis to create a **grid-like overlay** on the start of the application

- Added **"showGuides"** prop to **hide and show gridlines** - (passing true or false will toggle gridlines)

### CODE REVIEW

**Comment by daybrush** [comment]
@sajanthomas01 

What about defaultGuides rather than the name guidePreset?

**Comment by sajanthomas01** [comment]
> @sajanthomas01
> 
> What about defaultGuides rather than the name guidePreset?

Sure, I'll change it to defaultGuides

**Comment by sajanthomas01** [comment]
> > @sajanthomas01
> > What about defaultGuides rather than the name guidePreset?
> 
> Sure, I'll change it to defaultGuides

renamed to defaultGuides

**Comment by daybrush** [comment]
@sajanthomas01 

I'll release within this week. Thank you :)

**Comment by sajanthomas01** [comment]
> @sajanthomas01
> 
> I'll release within this week. Thank you :)

Thanks buddy :)

**Comment by daybrush** [comment]
Duplicated of #23 

I will close this.

**Pull request closed without merging**
